### ISSUE TITLE
mode choice tests need to run on jenkins first before trying to enable them on master again

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#427] opened 2018-08-23 23:26 UTC

**Comment by colinsheppard** [comment] 2018-08-28 14:41
This issue was mostly addressed in #435  

Still remaining: enable and update ModeChoiceSpec which needs to include specific intercept terms in the custom configuration at start of test

**Comment by colinsheppard** [comment] 2018-08-28 14:42
Actually, MultinomialCustomConfigSpec covers what was intended by ModeChoiceSpec....

I'm going to just delete ModeChoiceSpec in my current feature branch and close this issue.

**Comment by wrashid** [comment] 2018-08-28 18:09
RealizedModeGraphTest and ModeChosenGraphTest => re-enable disabled tests

**Closed** 2018-08-30 17:14 UTC
Labels: in progress
