### ISSUE TITLE
Tests: improved summary at the end of spec run

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3414] opened 2021-12-14 15:40 UTC
It might be hard to find what tests had failed because they are scattered across full spec log.
We need to improve test task so it will give a list of failed specs in the summary at the end.

**Comment by JustinPihony** [comment] 2021-12-28 22:33
Duplicate of #3396

**Closed as completed by JustinPihony** 2021-12-28 22:33 UTC
