### ISSUE TITLE
Enable Reproducibility

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#145] opened 2017-11-08 17:57 UTC
We need our testing framework to operate in fully reproducible mode. This will require configuring akka to dispatch in a deterministic manner and to collapse the scheduler down to 1 sec window and to initialize all random number generators with a seed.

**Comment by michaz** [comment] 2017-11-09 00:46
Prerequisite to 

> configuring akka to dispatch in a deterministic manner

is changing the way the scheduler waits for messages within a timestep. See the disabled scheduler test and my comment -- I think, when going single-threaded, the current implementation translates into an infinite loop of sending DoSimStep(t) messages, without the message which would allow progress having a chance of getting in.

**Comment by michaz** [comment] 2017-11-09 00:49
(Not sure though.)

**Comment by colinsheppard** [comment] 2017-11-09 00:50
I'm not so sure either... the idea behind sending a message to itself is precisely to give other messages a chance to get into the mailbox ahead of the next DoSimStep message.

**Comment by michaz** [comment] 2017-11-13 13:36
> (Not sure though.)

Now I am sure. Fixed in #151.

**Comment by michaz** [comment] 2017-11-13 13:37
We shouldn't be using global random number generators, but every agent should have its own source of randomness. Then, if everything else is correct, we get reproducible runs also in production, not only in testing.

**Comment by colinsheppard** [comment] 2018-06-27 22:23
@JustinPihony this feels like a good one for you. First off, can you confirm whether how we can force reproducibility in how akka dispatches messages? I.e. can we force it into single threaded mode?

**Comment by JustinPihony** [comment] 2018-06-28 05:12
Hrmmm, I'd like to take a look at the tests first. Are there any in particular that are unpredictable, so I can focus on that? We can probably set the parallelism factor down, but this is something which is usually frowned upon, even for testing. It doesn't give the best indication of how the system works as a whole. So, I guess this comes a bit down to whether this is for unit tests or integration tests. But, first and foremost is a specific example of a flaky test - that can help me figure if the problem is something that is only handled by going single threaded or if there is a better means to enable reproducibility.

**Comment by carloscaldas** [comment] 2021-05-28 21:57
Maybe implement later

**Closed by carloscaldas** 2021-05-28 21:57 UTC
Labels: Maybe implement later
