### ISSUE TITLE
NYC: Graph per input parameter for all the month which we model

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2968] opened 2020-09-04 16:36 UTC
Graph per parameter:
- WALK_INTERCEPT
- additional trip utility
- industries removal probability
- Crowdedness (it it works)

Until July

**Comment by nikolayilyin** [comment] 2020-09-05 23:07
looks like it is a duplicate of https://github.com/LBNL-UCB-STI/beam/issues/2971

**Closed by nikolayilyin** 2020-09-05 23:07 UTC
