### ISSUE TITLE
Documentation: Add information about warm start.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3304] opened 2021-09-10 16:27 UTC
We are missing information about warmstart.
1. what the warmstart is.
2. what kind of warmstart we have.
3. how to configure simulation in order to prepare required files.
4. how to configure simulation in order to use warmstart files.

**Comment by nikolayilyin** [comment] 2021-10-07 15:49
There is Warm Mode section in our documentation but it looks outdated.
We have more than one type of warm start, it would be good to specify in documentation what the difference between them.

There is a shell file I used to generate warmstart archive src/main/bash/warmstart/prep-warmstart-new.sh

We need an instruction of how to configure simulation in order to prepare these files, i.e. configuration keys used to write required files. 
Also we have a configuration key to generate a warmstart archive at the end of simulation.

**Comment by alex-vv** [comment] 2022-09-13 11:53
duplicate of https://github.com/LBNL-UCB-STI/beam/issues/3423

**Closed as completed by alex-vv** 2022-09-13 11:53 UTC
