### ISSUE TITLE
Snap activities to links when loading them

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/beam#3483] opened 2022-03-08 17:31 UTC
Documenting a discussion with @nikolayilyin and @heyrutvik -- we might be able to avoid some of the issues with non-reproducible splits (and potentially save repeat computations) by preprocessing all activity locations to snap them to the nearest R5 link. I suppose that doing this could involve either replacing many usages of coordinates with a link Id, or it could involve replacing calls to `snapToR5Edge` with calls to a lookup table, or just building a cache within `getR5Split`

**Comment by heyrutvik** [comment] 2022-07-11 16:31
@nikolayilyin I believe this ticket is related to https://github.com/LBNL-UCB-STI/beam/issues/3489. In that case, we can close this one as well. Here is the related PR: https://github.com/LBNL-UCB-STI/beam/pull/3513 which does snap activity locations too.

**Comment by nikolayilyin** [comment] 2022-07-11 18:20
Closed as duplicate of #3489

**Closed as completed by nikolayilyin** 2022-07-11 18:20 UTC
